# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 503f0bce5220972a898c3dade5d78ef96323e7e630b4945d5b31b633b7f5f7b997c3cfcaa89135e51106b9571a8b7acb15f45b9b7174785b76348d489062ae8f

test:
  secret_key_base: b938340724acb0ffa480348f84fe977907109a3374ba3d65257d6156ede8e227659a4a8533785158e027fc175c2b6f12be3ca9fd06e768b8adf78f1b56ca6535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
